
CREATE TABLE COM_FILE_CONFG
(
   FILE_CONFIG_ID INTEGER(10) PRIMARY KEY,
   USER_ID VARCHAR(20) NOT NULL,
   USER_TYPE VARCHAR(20) NOT NULL,
   FILE_STRUCT VARCHAR(20) NOT NULL,
   FILE_DLMTR VARCHAR(1),
   INVC_NMBR VARCHAR(10) NOT NULL,
   INVC_AMNT VARCHAR(10) NOT NULL,
   INVC_DATE VARCHAR(10) NOT NULL,
   VNDR_CODE VARCHAR(10) NOT NULL,
   VNDR_NAME VARCHAR(10) NOT NULL,
   DUE_DATE VARCHAR(10) NOT NULL,
   PYMT_IDFR VARCHAR(10) NOT NULL,
   PRCSSNG_DATE VARCHAR(10) NOT NULL,
   ADDITIONAL_FIELD_1 VARCHAR(50),
   ADDITIONAL_FIELD_2 VARCHAR(50),
   ADDITIONAL_FIELD_3 VARCHAR(50),
   ADDITIONAL_FIELD_4 VARCHAR(50),
   ADDITIONAL_FIELD_5 VARCHAR(50),
   ADDITIONAL_FIELD_6 VARCHAR(50),
   ADDITIONAL_FIELD_7 VARCHAR(50),
   ADDITIONAL_FIELD_8 VARCHAR(50),
   ADDITIONAL_FIELD_9 VARCHAR(50),
   ADDITIONAL_FIELD_10 VARCHAR(50),
   CREATED_BY VARCHAR(100),
   CREATED TIMESTAMP,
   UPDATED TIMESTAMP,
   UPDATED_BY VARCHAR(100)
);


CREATE TABLE DEALER_FIN_TXN_DTLS
(
	INVOICE_NO VARCHAR(20),
	INVOICE_AMT NUMBER(100,2),
	INVOICE_DATE TIMESTAMP,
	DEALER_CODE VARCHAR(20),
	DEALER_NAME VARCHAR(100),
	PRCSNG_DATE TIMESTAMP,
	DEALER_REF_NO VARCHAR(50),
	ADDITIONAL_FIELD_1 VARCHAR(255),
	ADDITIONAL_FIELD_2 VARCHAR(255),
	ADDITIONAL_FIELD_3 VARCHAR(255),
	ADDITIONAL_FIELD_4 VARCHAR(255),
	ADDITIONAL_FIELD_5 VARCHAR(255),
	ADDITIONAL_FIELD_6 VARCHAR(255),
	ADDITIONAL_FIELD_7 VARCHAR(255),
	ADDITIONAL_FIELD_8 VARCHAR(255),
	ADDITIONAL_FIELD_9 VARCHAR(255),
	ADDITIONAL_FIELD_10 VARCHAR(255)
);

CREATE TABLE VENDOR_FIN_TXN_DTLS
(
	INVOICE_NO VARCHAR(20),
	INVOICE_AMT NUMBER(100,2),
	INVOICE_DATE TIMESTAMP,
	VENDOR_CODE VARCHAR(20),
	VENDOR_NAME VARCHAR(100),
	PRCSNG_DATE TIMESTAMP,
	PYMNT_IDFR VARCHAR(50),
	DUE_DATE TIMESTAMP,
	ADDITIONAL_FIELD_1 VARCHAR(255),
	ADDITIONAL_FIELD_2 VARCHAR(255),
	ADDITIONAL_FIELD_3 VARCHAR(255),
	ADDITIONAL_FIELD_4 VARCHAR(255),
	ADDITIONAL_FIELD_5 VARCHAR(255),
	ADDITIONAL_FIELD_6 VARCHAR(255),
	ADDITIONAL_FIELD_7 VARCHAR(255),
	ADDITIONAL_FIELD_8 VARCHAR(255),
	ADDITIONAL_FIELD_9 VARCHAR(255),
	ADDITIONAL_FIELD_10 VARCHAR(255)
);

CREATE TABLE FILE_UPLOAD_DETAILS(

	IM_CODE VARCHAR(20),
	FILE_ID VARCHAR(20),
	FILE_NAME VARCHAR(100),
	FILE_STATUS VARCHAR(20),
	FILE_TYPE VARCHAR(10),
	FILE_GUID VARCHAR(65),
	CREATED_BY VARCHAR(100),
   	CREATED TIMESTAMP,
   	UPDATED TIMESTAMP,
   	UPDATED_BY VARCHAR(100)
);
