CREATE TABLE COM_VENDOR_TXN_INVC
(	
	TXN_INVC_ID NUMBER,
	INVC_NMBR VARCHAR(50),
	INVC_AMNT NUMBER(100,2),
	INVC_DATE TIMESTAMP,
	VNDR_CODE VARCHAR(20),
	VNDR_NAME VARCHAR(100),
	DUE_DATE TIMESTAMP,
	PYMT_IDFR VARCHAR(20),
	PRCSSNG_DATE TIMESTAMP,
	INVC_STATUS VARCHAR(20),
	ADDITIONAL_FIELD_1 VARCHAR(255),
	ADDITIONAL_FIELD_2 VARCHAR(255),
	ADDITIONAL_FIELD_3 VARCHAR(255),
	ADDITIONAL_FIELD_4 VARCHAR(255),
	ADDITIONAL_FIELD_5 VARCHAR(255),
	ADDITIONAL_FIELD_6 VARCHAR(255),
	ADDITIONAL_FIELD_7 VARCHAR(255),
	ADDITIONAL_FIELD_8 VARCHAR(255),
	ADDITIONAL_FIELD_9 VARCHAR(255),
	ADDITIONAL_FIELD_10 VARCHAR(255),
	CREATED TIMESTAMP,
	CREATED_BY VARCHAR(100),
	UPDATED TIMESTAMP,
	UPDATED_BY VARCHAR(100)
);

CREATE INDEX "BVSBI"."COM_VENDOR_TXN_INVC" ON "BVSBI"."COM_VENDOR_TXN_INVC" ("INVC_NMBR");

ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" ADD CONSTRAINT "COM_VENDOR_TXN_INVC" PRIMARY KEY ("TXN_INVC_ID") ENABLE;


ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("INVC_NMBR" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("INVC_AMNT" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("INVC_DATE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("VNDR_CODE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("VNDR_NAME" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("DUE_DATE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("PYMT_IDFR" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("PRCSSNG_DATE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("CREATED" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("UPDATED" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_VENDOR_TXN_INVC" MODIFY ("UPDATED_BY" NOT NULL ENABLE);