CREATE TABLE COM_FILE_UPLD_DTLS
(
	FILE_ID NUMBER,
	IM_CODE VARCHAR(20),
	FILE_NAME VARCHAR(100),
	FILE_STATUS VARCHAR(20),
	FILE_TYPE VARCHAR(20),
	FILE_GUID VARCHAR(20),
	FILE_HASH VARCHAR(64),
	INVOICE_COUNT NUMBER,
	TOTAL_AMOUNT NUMBER(100,2),
	CREATED TIMESTAMP,
	CREATED_BY VARCHAR(100),
	UPDATED TIMESTAMP,
	UPDATED_BY VARCHAR(100)
);

CREATE INDEX "BVSBI"."COM_FILE_UPLD_DTLS_IDX" ON "BVSBI"."COM_FILE_UPLD_DTLS" ("IM_CODE");

ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" ADD CONSTRAINT "PK_COM_FILE_UPLD_DTLS" PRIMARY KEY ("FILE_ID") ENABLE;

ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("IM_CODE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("FILE_STATUS" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("FILE_GUID" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("FILE_HASH" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("INVOICE_COUNT" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("CREATED" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("UPDATED" NOT NULL ENABLE);
ALTER TABLE "BVSBI"."COM_FILE_UPLD_DTLS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
